// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrZoO8RxQVXWxUlsx8d6LdMBAcaqpSjQ',
    appId: '1:874530419434:web:c0c20e737b6db911f85d93',
    messagingSenderId: '874530419434',
    projectId: 'chat-app-project-9d35c',
    authDomain: 'chat-app-project-9d35c.firebaseapp.com',
    storageBucket: 'chat-app-project-9d35c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzC5D9Gg35JSRVjj6hcsdrD0PX67reQBs',
    appId: '1:874530419434:android:4c2dc3c85421fb4ef85d93',
    messagingSenderId: '874530419434',
    projectId: 'chat-app-project-9d35c',
    storageBucket: 'chat-app-project-9d35c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxdt7Li3MEP8PJcArhOEhrnk3ZvuRBqsI',
    appId: '1:874530419434:ios:31014a07eba23668f85d93',
    messagingSenderId: '874530419434',
    projectId: 'chat-app-project-9d35c',
    storageBucket: 'chat-app-project-9d35c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxdt7Li3MEP8PJcArhOEhrnk3ZvuRBqsI',
    appId: '1:874530419434:ios:ff7dfd8e1fb98956f85d93',
    messagingSenderId: '874530419434',
    projectId: 'chat-app-project-9d35c',
    storageBucket: 'chat-app-project-9d35c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
